import { Product } from "@/types/product";

const now = new Date().toISOString();

const categories = {
  shoes: {
    id: 1,
    name: "shoes",
    slug: "shoes",
    creationAt: now,
    updatedAt: now,
  },
  clothing: {
    id: 2,
    name: "clothing",
    slug: "clothing",
    creationAt: now,
    updatedAt: now,
  },
  electronics: {
    id: 3,
    name: "electronics",
    slug: "electronics",
    creationAt: now,
    updatedAt: now,
  },
  home: {
    id: 4,
    name: "home",
    slug: "home",
    creationAt: now,
    updatedAt: now,
  },
  accessories: {
    id: 5,
    name: "accessories",
    slug: "accessories",
    creationAt: now,
    updatedAt: now,
  },
};

export const products: Product[] = [
  {
    id: 1,
    title: "Running Shoes Nike Air Zoom",
    price: 120,
    category: categories.shoes,
    images: ["/images/products/running-shoes-nike-air-zoom.jpg"],
    rating: 4.6,
  },
  {
    id: 2,
    title: "Adidas Ultraboost 22",
    price: 140,
    category: categories.shoes,
    images: ["/images/products/adidas-ultraboost-22.jpg"],
    rating: 4.7,
  },
  {
    id: 3,
    title: "Basic White T-Shirt",
    price: 25,
    category: categories.clothing,
    images: ["/images/products/basic-white-tshirt.jpg"],
    rating: 4.3,
  },
  {
    id: 4,
    title: "Black Hoodie Oversized",
    price: 60,
    category: categories.clothing,
    images: ["/images/products/black-hoodie-oversized.jpg"],
    rating: 4.5,
  },
  {
    id: 5,
    title: "Slim Fit Blue Jeans",
    price: 80,
    category: categories.clothing,
    images: ["/images/products/slim-fit-blue-jeans.jpg"],
    rating: 4.4,
  },
  {
    id: 6,
    title: "Apple AirPods Pro",
    price: 250,
    category: categories.electronics,
    images: ["/images/products/apple-airpods-pro.jpg"],
    rating: 4.8,
  },
  {
    id: 7,
    title: "Sony WH-1000XM5 Headphones",
    price: 350,
    category: categories.electronics,
    images: ["/images/products/sony-wh1000xm5.jpg"],
    rating: 4.9,
  },
  {
    id: 8,
    title: "Mechanical Keyboard RGB",
    price: 110,
    category: categories.electronics,
    images: ["/images/products/mechanical-keyboard-rgb.jpg"],
    rating: 4.6,
  },
  {
    id: 9,
    title: "Gaming Mouse Logitech G502",
    price: 90,
    category: categories.electronics,
    images: ["/images/products/logitech-g502-mouse.jpg"],
    rating: 4.7,
  },
  {
    id: 10,
    title: "4K Monitor 27 Inch",
    price: 400,
    category: categories.electronics,
    images: ["/images/products/4k-monitor-27.jpg"],
    rating: 4.6,
  },
  {
    id: 11,
    title: "Wooden Coffee Table",
    price: 180,
    category: categories.home,
    images: ["/images/products/wooden-coffee-table.jpg"],
    rating: 4.4,
  },
  {
    id: 12,
    title: "Ergonomic Office Chair",
    price: 220,
    category: categories.home,
    images: ["/images/products/ergonomic-office-chair.jpg"],
    rating: 4.7,
  },
  {
    id: 13,
    title: "Minimalist Desk Lamp",
    price: 45,
    category: categories.home,
    images: ["/images/products/minimalist-desk-lamp.jpg"],
    rating: 4.3,
  },
  {
    id: 14,
    title: "Smart LED Light Strip",
    price: 35,
    category: categories.home,
    images: ["/images/products/smart-led-strip.jpg"],
    rating: 4.5,
  },
  {
    id: 15,
    title: "Fitness Smartwatch",
    price: 150,
    category: categories.electronics,
    images: ["/images/products/fitness-smartwatch.jpg"],
    rating: 4.4,
  },
  {
    id: 16,
    title: "Leather Backpack",
    price: 130,
    category: categories.accessories,
    images: ["/images/products/leather-backpack.jpg"],
    rating: 4.6,
  },
  {
    id: 17,
    title: "Classic Sunglasses",
    price: 70,
    category: categories.accessories,
    images: ["/images/products/classic-sunglasses.jpg"],
    rating: 4.3,
  },
  {
    id: 18,
    title: "Stainless Steel Water Bottle",
    price: 30,
    category: categories.accessories,
    images: ["/images/products/water-bottle-steel.jpg"],
    rating: 4.5,
  },
];
